
server:
  port: 8088

zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8090/api
    web:
      path: /**
      url: http://localhost:8083/
    auth:
      path: /auth/login
      url: http://localhost:8083/auth/login
    reg:
      path: /auth/registration
      url: http://localhost:8083/auth/registration
